// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/metronome-go-sdk/internal/utils"
	"github.com/speakeasy-sdks/metronome-go-sdk/models/components"
	"time"
)

type ListRateCardsRequestBody struct {
}

type ListRateCardsRequest struct {
	// Max number of results that should be returned
	Limit *int64 `queryParam:"style=form,explode=true,name=limit"`
	// Cursor that indicates where the next page of results should start.
	NextPage    *string                   `queryParam:"style=form,explode=true,name=next_page"`
	RequestBody *ListRateCardsRequestBody `request:"mediaType=application/json"`
}

func (o *ListRateCardsRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *ListRateCardsRequest) GetNextPage() *string {
	if o == nil {
		return nil
	}
	return o.NextPage
}

func (o *ListRateCardsRequest) GetRequestBody() *ListRateCardsRequestBody {
	if o == nil {
		return nil
	}
	return o.RequestBody
}

type ListRateCardsFiatCreditType struct {
	Name string `json:"name"`
	ID   string `json:"id"`
}

func (o *ListRateCardsFiatCreditType) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *ListRateCardsFiatCreditType) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type ListRateCardsCustomCreditType struct {
	Name string `json:"name"`
	ID   string `json:"id"`
}

func (o *ListRateCardsCustomCreditType) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *ListRateCardsCustomCreditType) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type ListRateCardsCreditTypeConversions struct {
	FiatPerCustomCredit string                        `json:"fiat_per_custom_credit"`
	CustomCreditType    ListRateCardsCustomCreditType `json:"custom_credit_type"`
}

func (o *ListRateCardsCreditTypeConversions) GetFiatPerCustomCredit() string {
	if o == nil {
		return ""
	}
	return o.FiatPerCustomCredit
}

func (o *ListRateCardsCreditTypeConversions) GetCustomCreditType() ListRateCardsCustomCreditType {
	if o == nil {
		return ListRateCardsCustomCreditType{}
	}
	return o.CustomCreditType
}

type ListRateCardsAliases struct {
	Name         string     `json:"name"`
	StartingAt   *time.Time `json:"starting_at,omitempty"`
	EndingBefore *time.Time `json:"ending_before,omitempty"`
}

func (l ListRateCardsAliases) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListRateCardsAliases) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ListRateCardsAliases) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *ListRateCardsAliases) GetStartingAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.StartingAt
}

func (o *ListRateCardsAliases) GetEndingBefore() *time.Time {
	if o == nil {
		return nil
	}
	return o.EndingBefore
}

type ListRateCardsData struct {
	ID                    string                               `json:"id"`
	Name                  string                               `json:"name"`
	CreatedAt             time.Time                            `json:"created_at"`
	CreatedBy             string                               `json:"created_by"`
	Description           *string                              `json:"description,omitempty"`
	FiatCreditType        *ListRateCardsFiatCreditType         `json:"fiat_credit_type,omitempty"`
	CreditTypeConversions []ListRateCardsCreditTypeConversions `json:"credit_type_conversions,omitempty"`
	Aliases               []ListRateCardsAliases               `json:"aliases,omitempty"`
	CustomFields          map[string]string                    `json:"custom_fields,omitempty"`
}

func (l ListRateCardsData) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListRateCardsData) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ListRateCardsData) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *ListRateCardsData) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *ListRateCardsData) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *ListRateCardsData) GetCreatedBy() string {
	if o == nil {
		return ""
	}
	return o.CreatedBy
}

func (o *ListRateCardsData) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *ListRateCardsData) GetFiatCreditType() *ListRateCardsFiatCreditType {
	if o == nil {
		return nil
	}
	return o.FiatCreditType
}

func (o *ListRateCardsData) GetCreditTypeConversions() []ListRateCardsCreditTypeConversions {
	if o == nil {
		return nil
	}
	return o.CreditTypeConversions
}

func (o *ListRateCardsData) GetAliases() []ListRateCardsAliases {
	if o == nil {
		return nil
	}
	return o.Aliases
}

func (o *ListRateCardsData) GetCustomFields() map[string]string {
	if o == nil {
		return nil
	}
	return o.CustomFields
}

// ListRateCardsResponseBody - Success
type ListRateCardsResponseBody struct {
	Data     []ListRateCardsData `json:"data"`
	NextPage *string             `json:"next_page"`
}

func (o *ListRateCardsResponseBody) GetData() []ListRateCardsData {
	if o == nil {
		return []ListRateCardsData{}
	}
	return o.Data
}

func (o *ListRateCardsResponseBody) GetNextPage() *string {
	if o == nil {
		return nil
	}
	return o.NextPage
}

type ListRateCardsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	Object *ListRateCardsResponseBody

	Next func() (*ListRateCardsResponse, error)
}

func (o *ListRateCardsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListRateCardsResponse) GetObject() *ListRateCardsResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
