// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/metronome-go-sdk/models/components"
)

// SetRateCardProductsOrderRequestBody - New rate card product ordering
type SetRateCardProductsOrderRequestBody struct {
	// ID of the rate card to update
	RateCardID   string   `json:"rate_card_id"`
	ProductOrder []string `json:"product_order"`
}

func (o *SetRateCardProductsOrderRequestBody) GetRateCardID() string {
	if o == nil {
		return ""
	}
	return o.RateCardID
}

func (o *SetRateCardProductsOrderRequestBody) GetProductOrder() []string {
	if o == nil {
		return []string{}
	}
	return o.ProductOrder
}

type SetRateCardProductsOrderData struct {
	ID string `json:"id"`
}

func (o *SetRateCardProductsOrderData) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

// SetRateCardProductsOrderResponseBody - Success
type SetRateCardProductsOrderResponseBody struct {
	Data SetRateCardProductsOrderData `json:"data"`
}

func (o *SetRateCardProductsOrderResponseBody) GetData() SetRateCardProductsOrderData {
	if o == nil {
		return SetRateCardProductsOrderData{}
	}
	return o.Data
}

type SetRateCardProductsOrderResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	Object *SetRateCardProductsOrderResponseBody
}

func (o *SetRateCardProductsOrderResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *SetRateCardProductsOrderResponse) GetObject() *SetRateCardProductsOrderResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
