// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"github.com/Metronome-Industries/metronome-go-sdk/models/components"
)

// AddRatesContractsResponseBody - The specified resource was not found
type AddRatesContractsResponseBody struct {
	Message  string                  `json:"message"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &AddRatesContractsResponseBody{}

func (e *AddRatesContractsResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// AddRatesResponseBody - Bad request
type AddRatesResponseBody struct {
	Message  string                  `json:"message"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &AddRatesResponseBody{}

func (e *AddRatesResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
