// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
)

// BadRequest - Bad request
type BadRequest struct {
}

var _ error = &BadRequest{}

func (e *BadRequest) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
