// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"github.com/speakeasy-sdks/metronome-go-sdk/models/components"
)

// DisableCommitTrueupContractsResponseBody - The specified resource was not found
type DisableCommitTrueupContractsResponseBody struct {
	Message  string                  `json:"message"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &DisableCommitTrueupContractsResponseBody{}

func (e *DisableCommitTrueupContractsResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// DisableCommitTrueupResponseBody - Bad request
type DisableCommitTrueupResponseBody struct {
	Message  string                  `json:"message"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &DisableCommitTrueupResponseBody{}

func (e *DisableCommitTrueupResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
