// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"github.com/Metronome-Industries/metronome-go-sdk/models/components"
)

// SetCustomerBillableStatusContractsResponseBody - The specified resource was not found
type SetCustomerBillableStatusContractsResponseBody struct {
	Message  string                  `json:"message"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &SetCustomerBillableStatusContractsResponseBody{}

func (e *SetCustomerBillableStatusContractsResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// SetCustomerBillableStatusResponseBody - Bad request
type SetCustomerBillableStatusResponseBody struct {
	Message  string                  `json:"message"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &SetCustomerBillableStatusResponseBody{}

func (e *SetCustomerBillableStatusResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
