// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"github.com/Metronome-Industries/metronome-go-sdk/models/components"
)

// UpdateCreditEndDateContractsResponseBody - The specified resource was not found
type UpdateCreditEndDateContractsResponseBody struct {
	Message  string                  `json:"message"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &UpdateCreditEndDateContractsResponseBody{}

func (e *UpdateCreditEndDateContractsResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// UpdateCreditEndDateResponseBody - Bad request
type UpdateCreditEndDateResponseBody struct {
	Message  string                  `json:"message"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &UpdateCreditEndDateResponseBody{}

func (e *UpdateCreditEndDateResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
