// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"github.com/Metronome-Industries/metronome-go-sdk/models/components"
)

// UpdateProductContractsResponseBody - The specified resource was not found
type UpdateProductContractsResponseBody struct {
	Message  string                  `json:"message"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &UpdateProductContractsResponseBody{}

func (e *UpdateProductContractsResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// UpdateProductResponseBody - Bad request
type UpdateProductResponseBody struct {
	Message  string                  `json:"message"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &UpdateProductResponseBody{}

func (e *UpdateProductResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
