// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"github.com/Metronome-Industries/metronome-go-sdk/models/components"
)

// UpdateContractEndDateContractsResponseBody - The specified resource was not found
type UpdateContractEndDateContractsResponseBody struct {
	Message  string                  `json:"message"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &UpdateContractEndDateContractsResponseBody{}

func (e *UpdateContractEndDateContractsResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// UpdateContractEndDateResponseBody - Bad request
type UpdateContractEndDateResponseBody struct {
	Message  string                  `json:"message"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &UpdateContractEndDateResponseBody{}

func (e *UpdateContractEndDateResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
