// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package tests

import (
	"context"
	metronomegosdk "github.com/speakeasy-sdks/metronome-go-sdk"
	"github.com/speakeasy-sdks/metronome-go-sdk/models/operations"
	"github.com/speakeasy-sdks/metronome-go-sdk/types"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func TestContracts_UpdateInvoiceIssueDate_(t *testing.T) {
	s := metronomegosdk.New(
		metronomegosdk.WithSecurity("<YOUR_BEARER_TOKEN_HERE>"),
	)
	var request *operations.UpdateInvoiceIssueDateRequestBody = &operations.UpdateInvoiceIssueDateRequestBody{
		InvoiceID: "13117714-3f05-48e5-a6e9-a66093f13b4d",
		IssueDate: types.MustTimeFromString("2020-01-01T00:00:00.000Z"),
	}
	ctx := context.Background()
	res, err := s.Contracts.UpdateInvoiceIssueDate(ctx, request)
	require.NoError(t, err)
	assert.Equal(t, 200, res.HTTPMeta.Response.StatusCode)
	assert.Equal(t, operations.UpdateInvoiceIssueDateResponseBody{
		Data: operations.UpdateInvoiceIssueDateData{
			ID: "d7abd0cd-4ae9-4db7-8676-e986a4ebd8dc",
		},
	}, *res.Object)
}

func TestContracts_CreateHistoricalContractUsageInvoices_(t *testing.T) {
	assert.Fail(t, "incomplete test found please make sure to address the following errors: [`missing response values`]")
}
