// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package tests

import (
	"context"
	metronomegosdk "github.com/speakeasy-sdks/metronome-go-sdk"
	"github.com/speakeasy-sdks/metronome-go-sdk/models/operations"
	"github.com/speakeasy-sdks/metronome-go-sdk/types"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func TestCustomerCredits_ListCustomerCredits_(t *testing.T) {
	s := metronomegosdk.New(
		metronomegosdk.WithSecurity("<YOUR_BEARER_TOKEN_HERE>"),
	)
	var request *operations.ListCustomerCreditsRequestBody = &operations.ListCustomerCreditsRequestBody{
		CustomerID:     "13117714-3f05-48e5-a6e9-a66093f13b4d",
		CreditID:       metronomegosdk.String("6162d87b-e5db-4a33-b7f2-76ce6ead4e85"),
		IncludeLedgers: metronomegosdk.Bool(true),
	}
	ctx := context.Background()
	res, err := s.CustomerCredits.List(ctx, request)
	require.NoError(t, err)
	assert.Equal(t, 200, res.HTTPMeta.Response.StatusCode)
	assert.Equal(t, operations.ListCustomerCreditsResponseBody{
		Data: []operations.ListCustomerCreditsData{
			operations.ListCustomerCreditsData{
				ID:       "fa411f5b-fb85-4755-9d4d-530717be083c",
				Type:     operations.ListCustomerCreditsTypeCredit,
				Name:     metronomegosdk.String("My test credit"),
				Priority: metronomegosdk.Float64(100),
				Product: operations.ListCustomerCreditsProduct{
					ID:   "2e30f074-d04c-412e-a134-851ebfa5ceb2",
					Name: "My product A",
				},
				AccessSchedule: &operations.ListCustomerCreditsAccessSchedule{
					CreditType: &operations.ListCustomerCreditsCreditType{
						Name: "USD (cents)",
						ID:   "2714e483-4ff1-48e4-9e25-ac732e8f24f2",
					},
					ScheduleItems: []operations.ListCustomerCreditsScheduleItems{
						operations.ListCustomerCreditsScheduleItems{
							ID:           "2d45952c-5a6e-43a9-8aab-f61ee21be81a",
							Amount:       10000000,
							StartingAt:   types.MustTimeFromString("2020-02-01T00:00:00.000Z"),
							EndingBefore: types.MustTimeFromString("2021-02-01T00:00:00.000Z"),
						},
					},
				},
				Description: metronomegosdk.String("My test credit description"),
				ApplicableProductIds: []string{
					"13a2179b-f0cb-460b-85a1-cd42964ca533",
				},
				ApplicableContractIds: []string{
					"d7abd0cd-4ae9-4db7-8676-e986a4ebd8dc",
				},
				Ledger: []operations.ListCustomerCreditsLedger{
					operations.CreateListCustomerCreditsLedgerLedger2(
						operations.Ledger2{
							Type:      operations.ListCustomerCreditsLedgerCustomerCreditsTypeCreditAutomatedInvoiceDeduction,
							Timestamp: types.MustTimeFromString("2020-03-01T00:00:00.000Z"),
							Amount:    10000000,
							SegmentID: "2d45952c-5a6e-43a9-8aab-f61ee21be81a",
							InvoiceID: "525b9759-7bbd-4a05-aab1-d7c43c976b57",
						},
					),
				},
			},
		},
		NextPage: nil,
	}, *res.Object)
}

func TestCustomerCredits_CreateCustomerCredit_(t *testing.T) {
	s := metronomegosdk.New(
		metronomegosdk.WithSecurity("<YOUR_BEARER_TOKEN_HERE>"),
	)
	var request *operations.CreateCustomerCreditRequestBody = &operations.CreateCustomerCreditRequestBody{
		CustomerID: "13117714-3f05-48e5-a6e9-a66093f13b4d",
		Name:       metronomegosdk.String("My Credit"),
		Priority:   100,
		ProductID:  "f14d6729-6a44-4b13-9908-9387f1918790",
		AccessSchedule: operations.CreateCustomerCreditAccessSchedule{
			CreditTypeID: metronomegosdk.String("2714e483-4ff1-48e4-9e25-ac732e8f24f2"),
			ScheduleItems: []operations.CreateCustomerCreditScheduleItems{
				operations.CreateCustomerCreditScheduleItems{
					Amount:       1000,
					StartingAt:   types.MustTimeFromString("2020-01-01T00:00:00.000Z"),
					EndingBefore: types.MustTimeFromString("2020-02-01T00:00:00.000Z"),
				},
			},
		},
	}
	ctx := context.Background()
	res, err := s.CustomerCredits.Create(ctx, request)
	require.NoError(t, err)
	assert.Equal(t, 200, res.HTTPMeta.Response.StatusCode)
	assert.Equal(t, operations.CreateCustomerCreditResponseBody{
		Data: operations.CreateCustomerCreditData{
			ID: "6162d87b-e5db-4a33-b7f2-76ce6ead4e85",
		},
	}, *res.Object)
}

func TestCustomerCredits_UpdateCreditEndDate_(t *testing.T) {
	s := metronomegosdk.New(
		metronomegosdk.WithSecurity("<YOUR_BEARER_TOKEN_HERE>"),
	)
	var request *operations.UpdateCreditEndDateRequestBody = &operations.UpdateCreditEndDateRequestBody{
		CustomerID:         "13117714-3f05-48e5-a6e9-a66093f13b4d",
		CreditID:           "6162d87b-e5db-4a33-b7f2-76ce6ead4e85",
		AccessEndingBefore: types.MustTimeFromString("2020-01-01T00:00:00.000Z"),
	}
	ctx := context.Background()
	res, err := s.CustomerCredits.UpdateEndDate(ctx, request)
	require.NoError(t, err)
	assert.Equal(t, 200, res.HTTPMeta.Response.StatusCode)
	assert.Equal(t, operations.UpdateCreditEndDateResponseBody{
		Data: operations.UpdateCreditEndDateData{
			ID: "6162d87b-e5db-4a33-b7f2-76ce6ead4e85",
		},
	}, *res.Object)
}
