// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package tests

import (
	"context"
	metronomegosdk "github.com/speakeasy-sdks/metronome-go-sdk"
	"github.com/speakeasy-sdks/metronome-go-sdk/models/operations"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func TestInvoices_RegenerateInvoice_(t *testing.T) {
	s := metronomegosdk.New(
		metronomegosdk.WithSecurity("<YOUR_BEARER_TOKEN_HERE>"),
	)
	var request *operations.RegenerateInvoiceRequestBody = &operations.RegenerateInvoiceRequestBody{
		ID: "6a37bb88-8538-48c5-b37b-a41c836328bd",
	}
	ctx := context.Background()
	res, err := s.Invoices.Regenerate(ctx, request)
	require.NoError(t, err)
	assert.Equal(t, 200, res.HTTPMeta.Response.StatusCode)
	assert.Equal(t, operations.RegenerateInvoiceResponseBody{
		Data: &operations.RegenerateInvoiceData{
			ID: "6a37bb88-8538-48c5-b37b-a41c836328bd",
		},
	}, *res.Object)
}
