workflowVersion: 1.0.0
sources:
    Metronome-OAS:
        inputs:
            - location: https://api.metronome.com/v1/openapi/contracts.json
        overlays:
          - location: Speakeasy-Suggested-Overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/metronome/metronome/metronome-oas
targets:
    metronome:
        target: go
        source: Metronome-OAS
